[build]
  command = "cd frontend && rm -rf node_modules package-lock.json && npm install --legacy-peer-deps --force && npm run build"
  publish = "frontend/dist"
  environment = { NPM_FLAGS = "--legacy-peer-deps", NODE_VERSION = "22" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200