[build]
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps --force && npm run build"
  base = "frontend"
  publish = "dist"
  environment = { NPM_FLAGS = "--legacy-peer-deps", NODE_VERSION = "22", VITE_APP_URL = "https://cryptocampaign.netlify.app" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - but don't redirect assets
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = "Role=visitor"
  
# Ensure assets are served correctly
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"