ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS user_full_name TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS setup_step INTEGER DEFAULT 1;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS setup_completed BOOLEAN DEFAULT false;