# Supabase CLI config
project_ref = "kmepcdsklnnxokoimvzo"

[api]
url = "https://kmepcdsklnnxokoimvzo.supabase.co"

[db]
url = "postgresql://postgres.kmepcdsklnnxokoimvzo@aws-1-us-west-1.pooler.supabase.com:6543/postgres"